class AppConstant {
  static const String baseUrl = "https://yeti-steady-starling.ngrok-free.app/api";
  static const String baseImage = "https://yeti-steady-starling.ngrok-free.app/images/";
  static const String logIn = "$baseUrl/login";
  static const String addReport = "$baseUrl/prof/storeReport";
  static String? token;
  static String? role;
  static int? id;
  static String? idCourses;
  static bool color=false;

  static String t="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5IiwianRpIjoiODFiZjNiNDE2YmRmZjdiODg5OWRkYmVmNWJkYzMzNmE4OGRmYjZkMjY5MTBiYzdmMzcyYjMwMzQxMzRjNTRlZDU3ZmY2N2RhOTczNDU5YjgiLCJpYXQiOjE3MTk3OTYzNDcuOTQ1OTk5LCJuYmYiOjE3MTk3OTYzNDcuOTQ2MDAyLCJleHAiOjE3NTEzMzIzNDcuOTM2MTAyLCJzdWIiOiI5OCIsInNjb3BlcyI6W119.v1j1wYb3gICFbZ2rxrzVv1J5xE5jKS3lhzzgQYEflIQTo25aX9xB46Ip2bEswzmc1iUB8BJX0jXXxQ9jVUiuDslYyPJZAOp8o4OzKUuHl8AksxSpYBJDxsiKobK0QxMgAHUgOf3HK6ROBz-6KtRdY9K889GqmqOw2hmf8lpbzYWZvozGlDV1Db1pMFioRDC495zA8dbmrSITsKFwrU-iAXHAq6-moFp5wz0edVkyDwdlnr8sRNQ_lv_uDS9q36UUCRZuKshvNh0-sPBjNAjrolw2oDBIUMJmnlwPe_tpXIbll8-xPtgJ4UO6tMsM5sjQL34qDRm7KNN-ULIfxN4lGqTy-se2fR_blVIruSD1t2pK6tjloVQJ0-XEfYTcviajIymnZ-0YisuZogZfOolJBiCydNa-sjhwVgZuH9PGS2t7n2n1LEAx_cauK61fvr5TDSJIw_QMfE6wZau-u3eOisB5ENUbvf0kjLwD0Hmer_EI_Hbh_7sJFD1jODfL0vspBaClrFTEDETs4Pf5WJ19GtxqaLr155ShbXeSiKr80Iw7TZYhIxfOly5qGN6wt5TANiZceJJQwF8pqUBd9utcviOWMzBfLvcO4b7CM03YMTDGXq0zVKudvUXqpt9pCKrZ-8NpStQp8mkUdj7k7ZND1_kYFwVQ4nbpCN4i68pRxQY";

}
